version: "2.3"

services:

  nginx:
    depends_on:
      - php
    build:
      context: ./.docker/nginx
    volumes:
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - ./.docker/nginx/Config/project.conf:/etc/nginx/conf.d/project.conf:cached
      - ./PROJECT:/opt/project/
    networks:
      - magento2_network

  varnish:
    image: varnish:stable
    container_name: varnish
    volumes:
      - "./.docker/varnish/varnish.vcl:/etc/varnish/default.vcl"
    ports:
      - "8040:80"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G
    command: "-p default_keep=300"
    depends_on:
      - "nginx"
    networks:
      - magento2_network

  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile-Project
    expose:
      - 9000
    volumes:
      - ./PROJECT:/opt/project/
      - ./PROJECT/auth.json:/usr/local/.composer/auth.json
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    networks:
      - magento2_network

  phpcli:
    build:
      context: .docker/php-cli
      dockerfile: Dockerfile-Project
    expose:
      - 9010
    volumes:
      - ./PROJECT:/opt/project/
      - ./PROJECT/auth.json:/usr/local/.composer/auth.json
      - ./.docker/php-cli/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    networks:
      - magento2_network

  https-portal:
    image: steveltn/https-portal:1
    volumes:
      - ./.docker/certs:/var/lib/https-portal
    ports:
      - '80:80'
      - '443:443'
    links:
      - nginx
      - varnish
    environment:
      DOMAINS: 'local.magento2.com.br -> http://nginx:8040, local.magento2-store2.com.br -> http://nginx:8040'
      STAGE: 'local'
      FORCE_RENEW: 'false'
      PROXY_BUFFERS: '16 32k'
      PROXY_BUFFER_SIZE: '32k'
      CLIENT_MAX_BODY_SIZE: 64M
    networks:
      - magento2_network

  db:
    image: mariadb:10.6
    command: --max_allowed_packet=1G
#    shm_size: 2gb
    ports:
      - "3306:3306"
    env_file: ./.docker/db/db.env
    volumes:
      - ./.docker/db/_data:/var/lib/mysql
      - ./.docker/db/dump:/dump
    networks:
      - magento2_network

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - magento2_network

  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - magento2_network

  opensearch:
    image: 'magento/magento-cloud-docker-opensearch:2.5-1.3.6'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - discovery.seed_hosts=opensearch
      - bootstrap.memory_lock=true
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - '9200:9200'
    networks:
      - magento2_network

  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./.docker/mongo/w_data:/data/db
    ports:
        - 27017:27017
    networks:
      - magento2_network

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - magento2_network

volumes:
  elasticsearch-data:
    driver: local
networks:
  magento2_network:
    driver: bridge
