version: "2.2"

services:

  nginx:
    build:
      context: ./.docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/magento2.conf:cached
      - ./magento2:/app/code
    networks:
      magento2_oqvestir:
        aliases:
          - local.m2.com.br

  php:
    build:
      context: ./.docker/php
    expose:
      - 9000
    volumes:
      - ./magento2:/app/code
      - ./magento2/auth.json:/usr/local/.composer/auth.json
      - ./.docker/php/php.ini-development:/usr/local/etc/php/conf.d/php.ini
    networks:
      - magento2_network

  db:
    image: mariadb:10.4
    command: --max_allowed_packet=64M
    ports:
      - "3306:3306"
    env_file: ./.docker/db/db.env
    volumes:
      - ./.docker/db/_data:/var/lib/mysql
      #- /home/michel_silva/Documentos/Dev/mariadb_data:/var/lib/mysql
      #- /home/michel_silva/Documentos/Dev/MAGE2/DUMP:/dump
    networks:
      - magento2_network

  rabbitmq:
    image: rabbitmq:3.8.8-management
    ports:
      - "15672:15672"
    networks:
      - magento2_network

  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - magento2_network

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - "./.docker/elasticsearch/_data:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    networks:
      - magento2_network

  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./.docker/mongo/w_data:/data/db
    ports:
        - 27017:27017
    networks:
      - magento2_network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - magento2_network

networks:
  magento2_network:
    driver: bridge
