version: "2.3"

services:

  nginx:
    build:
      context: ./.docker/nginx
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - ./.docker/nginx/config/nginx-config.conf:/etc/nginx/conf.d/nginx-config.conf:cached
      - ./Projeto:/opt/project/:consistent
    depends_on:
      - redis
      - db
      - php
    networks:
      - magento2_network

  varnish:
    image: varnish:stable
    container_name: varnish
    volumes:
      - "./.docker/varnish/varnish.vcl:/etc/varnish/default.vcl"
    ports:
      - "8040:80"
    tmpfs:
      - /var/lib/varnish:exec
    extra_hosts:
      - "magento-cloud-tunnel:host-gateway"
    environment:
      - VARNISH_SIZE=2G
    command: "-p default_keep=300"
    depends_on:
      - "nginx"
    networks:
      - magento2_network

  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    depends_on:
      - redis
      - db
    expose:
      - 9000
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:cached
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./Projeto:/opt/project/:consistent
      - ./Projeto/auth.json:/usr/local/.composer/auth.json
    networks:
      - magento2_network

  phpcli:
    build:
      context: .docker/php-cli
      dockerfile: Dockerfile
    depends_on:
      - redis
      - db
    expose:
      - 9010
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:cached
      - ./.docker/php-cli/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./Projeto:/opt/project/:consistent
      - ./Projeto/auth.json:/usr/local/.composer/auth.json
    networks:
      - magento2_network

  https-portal:
    image: steveltn/https-portal:1
    volumes:
      - ./.temp/certs:/var/lib/https-portal
    ports:
      - '80:80'
      - '443:443'
    links:
      - nginx
      - varnish
    environment:
      DOMAINS: 'local.kuiper.com.br -> http://varnish:80'
      STAGE: 'local'
      FORCE_RENEW: 'false'
      PROXY_BUFFERS: '16 32k'
      PROXY_BUFFER_SIZE: '32k'
      CLIENT_MAX_BODY_SIZE: 64M
    networks:
      - magento2_network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=1G
    #    shm_size: 2gb
    ports:
      - "3306:3306"
    env_file: ./.docker/db/db.env
    volumes:
      - ./.temp/db/_data:/var/lib/mysql
      - ./.temp/db/dump:/dump
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pmagento"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped
    networks:
      - magento2_network

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - magento2_network

  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - magento2_network

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    networks:
      - magento2_network

  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./.temp/mongo/w_data:/data/db
    ports:
      - 27017:27017
    networks:
      - magento2_network

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - magento2_network

volumes:
  elasticsearch-data:
    driver: local
networks:
  magento2_network:
    driver: bridge
