FROM php:8.3-fpm

ARG ssh_prv_key
ARG ssh_pub_key

RUN apt-get update && apt-get install -y --no-install-recommends \
    libjpeg62-turbo-dev \
    libpng-dev \
    libxml2-dev \
    libxslt-dev \
    libsodium-dev \
    libzip-dev \
    libfreetype6-dev \
    git \
    unzip \
    cron \
    build-essential \
    supervisor \
    openssh-client \
    zip \
    wget \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
        pdo \
        pdo_mysql \
        gd \
        bcmath \
        intl \
        xsl \
        soap \
        sockets \
        simplexml \
        pcntl \
        exif \
        opcache \
        dom \
        zip \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 \
    && chmod +x mhsendmail_linux_amd64 \
    && mv mhsendmail_linux_amd64 /usr/local/bin/mhsendmail

COPY xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
COPY www.conf /usr/local/etc/php-fpm.d/www.conf

COPY --from=composer:2.7.2 /usr/bin/composer /usr/local/bin/composer

WORKDIR /opt/project/

CMD ["php-fpm"]
EXPOSE 9000
